version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    rebase-strategy: auto
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        versions:
          - "*-alpha*"
          - "*-beta*"
          - "*-rc*"

  - package-ecosystem: npm
    directory: "/"
    rebase-strategy: auto
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        versions:
          - "*-alpha*"
          - "*-beta*"
          - "*-rc*"
